### PR TITLE
update hd path

### PR DESCRIPTION
**Pull request by alienHunterOnMars**
Update hdpath used during client's wallet init to cointype 118

### CODE REVIEW

**Review by vishrutsingh — APPROVED** [review]
Looks good

**Comment by vishrutsingh** [comment]
Need to update package.json for new version

**Comment by alienHunterOnMars** [comment]
> Need to update package.json for new version @alienHunterOnMars

resolved

**Review by vishrutsingh — COMMENTED** [review]
updated version

**Review by vishrutsingh — APPROVED** [review]
approved

**Pull request merged**
